version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cpass
    container_name: cpass
    volumes:
      - ./data:/var/lib/postgresql/cpass/data
    ports:
      - 5432:5432
